# Generated by Django 4.2.4 on 2023-08-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='sanjik', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
