# Generated by Django 4.2.4 on 2023-08-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_owner',
        ),
    ]
